name = "mc-buildserver"
mc_version = "1.20.1"

[jar]
type = "fabric"
loader = "0.16.9"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "debugify"
version = "6XDJoCks"

[[mods]]
type = "modrinth"
id = "immediatelyfast"
version = "H62RYZyG"

[[mods]]
type = "modrinth"
id = "jade"
version = "Lvyx1o7I"

[[mods]]
type = "modrinth"
id = "jade-addons-fabric"
version = "DSkzT8Ma"

[[mods]]
type = "modrinth"
id = "log-begone"
version = "IknbjT7v"

[[mods]]
type = "modrinth"
id = "presence-footsteps"
version = "k0t6DSmw"

[[mods]]
type = "modrinth"
id = "create-steam-n-rails"
version = "VFhdqLko"

[[mods]]
type = "modrinth"
id = "xaeros-world-map"
version = "VXCG8MnU"

[[mods]]
type = "modrinth"
id = "another-furniture"
version = "YKKY0UDo"

[[mods]]
type = "modrinth"
id = "continuity"
version = "qGTDcjHM"

[[mods]]
type = "modrinth"
id = "create-fabric"
version = "7Ub71nPb"

[[mods]]
type = "modrinth"
id = "create-structures"
version = "nqsTHZwx"

[[mods]]
type = "modrinth"
id = "emi"
version = "7z8wc2Iv"

[[mods]]
type = "modrinth"
id = "entityculling"
version = "naHGCw23"

[[mods]]
type = "modrinth"
id = "extra-mod-integrations"
version = "IobIopQf"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "P7uGFii0"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "csX9r2wS"

[[mods]]
type = "modrinth"
id = "fallingleaves"
version = "flPXaySR"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "furnish-furniture"
version = "eGydI0NY"

[[mods]]
type = "modrinth"
id = "iam-music-player"
version = "p35CST3F"

[[mods]]
type = "modrinth"
id = "lazydfu"
version = "4SHylIO9"

[[mods]]
type = "modrinth"
id = "iris"
version = "Bi9nvICq"

[[mods]]
type = "modrinth"
id = "krypton"
version = "jiDwS0W1"

[[mods]]
type = "modrinth"
id = "lambdynamiclights"
version = "mYl4RvKg"

[[mods]]
type = "modrinth"
id = "lithium"
version = "ZSNsJrPI"

[[mods]]
type = "modrinth"
id = "memoryleakfix"
version = "5xvCCRjJ"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "rBUcyf7J"

[[mods]]
type = "modrinth"
id = "modmenu"
version = "lEkperf6"

[[mods]]
type = "modrinth"
id = "noisium"
version = "erSJnRcq"

[[mods]]
type = "modrinth"
id = "sound-physics-remastered"
version = "hxEab3Tk"

[[mods]]
type = "modrinth"
id = "spark"
version = "XGW2fviP"

[[mods]]
type = "modrinth"
id = "tectonic"
version = "8JhzXwo0"

[[mods]]
type = "modrinth"
id = "voice-chat-interaction"
version = "LX0uNyw4"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "IZhZbWUU"

[[mods]]
type = "modrinth"
id = "sodium"
version = "ygf8cVZg"
